version: "3.8"
name: hproxy-networks
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "3309:3309"
      - "3310:3310"
      - "5442:5442"
      - "5443:5443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      database_cluster:
        ipv4_address: 172.21.238.6

networks:
  database_cluster:
    name: database_cluster
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
          gateway: "172.21.0.1"
    attachable: true
