version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    ports:
      - "3307:3306"
    networks:
      - mysql_cluster

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_USER: repluser
      MYSQL_REPLICATION_PASSWORD: replpassword
    volumes:
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/data:/var/lib/mysql
      - ./slave/slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    networks:
      - mysql_cluster

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "3309:3309"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - mysql_cluster

networks:
  mysql_cluster:
    driver: bridge

volumes:
  master_data:
  slave_data:
