version: "1.0"

services:
  mysql-master1:
    image: mysql:8.0.37
    container_name: mysql-master1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./master1/data:/var/lib/mysql
      - ./master1/config:/etc/mysql/conf.d
      - ./master1/master1-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    ports:
      - "3307:3306"
    networks:
      database_cluster:
        ipv4_address: 172.21.238.2

  mysql-master2:
    image: mysql:8.0.37
    container_name: mysql-master2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_USER: repluser
      MYSQL_DATABASE: laravel
      MYSQL_REPLICATION_PASSWORD: replpassword
    volumes:
      - ./master2/data:/var/lib/mysql
      - ./master2/config:/etc/mysql/conf.d
      - ./master2/master2-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master1
    networks:
      database_cluster:
        ipv4_address: 172.21.238.3

networks:
  database_cluster:
    external:
      name: database_cluster

