version: "3.8"

services:
  postgres-master1:
    build: .
    container_name: postgres-master1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: laravel
    ports:
      - "5452:5432"
    volumes:
      - ./master1/data:/var/lib/postgresql/data
      - ./master1/master1-init.sql:/docker-entrypoint-initdb.d/master-init.sql
      - ./config/postgresql.conf:/usr/share/postgresql/postgresql.conf.sample
      - ./config/pg_hba.conf:/usr/share/postgresql/14/pg_hba.conf.sample
    networks:
      database_cluster:
        ipv4_address: 172.21.238.4

  postgres-master2:
    build: .
    container_name: postgres-master2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: laravel
    ports:
      - "5453:5432"
    volumes:
      - ./master2/data:/var/lib/postgresql/data
      - ./master2/master2-init.sql:/docker-entrypoint-initdb.d/master-init.sql
      - ./config/postgresql.conf:/usr/share/postgresql/postgresql.conf.sample
      - ./config/pg_hba.conf:/usr/share/postgresql/14/pg_hba.conf.sample
    networks:
      database_cluster:
        ipv4_address: 172.21.238.5
networks:
  database_cluster:
    external:
      name: database_cluster
